### PR TITLE
fix(activity): Disable notification mirror by default

### LINKED ISSUE #781: Announcements are always shown twice in notifications
### Steps to reproduce
1. Admin makes an announcement
2. Open notification box

### Expected behaviour
Only 1 notification per announcement.

### Actual behaviour
2 notifications per announcement:
image

### Server configuration
Current cloud.nc

### Client configuration
**Browser:** Firefox 123.0

**Operating system:** Ubuntu 22.04.4

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #781

### CODE REVIEW

File: lib/Activity/Setting.php [hunk 1]
```diff
@@ -49,35 +35,35 @@ public function getPriority(): int {
...
+	public function isDefaultEnabledNotification(): bool {
+		return false;
+	}
+
+	public function getGroupIdentifier(): string {
+		return 'other';
+	}
+
+	public function getGroupName(): string {
+		return 'Other activities';
```
Comment (solracsf) [inline lib/Activity/Setting.php:67]: Should be translated?

Comment (nickvergessen) [reply lib/Activity/Setting.php:67]: Since all `canChange*` are false, the entry will never display.
And at the same time it should be the group of server I think
