### PR TITLE
Log announcement creation and deletion

### LINKED ISSUE #381: Activity log for deletion of announcement
### Steps to reproduce
1. Make announcement
2. Delete the announcement 
3. There is no activity log for the deletion of the announcement

### Expected behaviour
The deletion activity should be shown in activity log with full detail like who deleted what, when... 
I really suggest to implement this one until this issue #193 get fixed. At least we can get who deleted the announcement. 

### Actual behaviour
There is no activity log for that 

Thank you!

### PR DESCRIPTION
**Pull request by tcitworld**
Closes #381

### CODE REVIEW

File: lib/Controller/APIController.php [hunk 1]
```diff
@@ -198,9 +191,23 @@ public function delete(int $id): DataResponse {
...
+
+			$this->logger->info('Admin ' . $userId . ' deleted announcement: "' . $announcement->getSubject() . '"');
+
+			return new DataResponse();
+		} catch (AnnouncementDoesNotExistException $e) {
+			return new DataResponse(
+				['message' => 'Announcement not found'],
+				Http::STATUS_NOT_FOUND
+			);
+		}
```
Comment (nickvergessen) [inline lib/Controller/APIController.php:210]: Let's keep the old APi behaviour of always returning 200 as 404 is not handled by the UI

```suggestion
			$this->logger->info('Admin ' . $userId . ' deleted announcement: "' . $announcement->getSubject() . '"');
		} catch (AnnouncementDoesNotExistException $e) {
		}
		
		return new DataResponse();
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]

**Review by nickvergessen — APPROVED** [review]
