### PR TITLE
Addresses #201 by fixing broken scroll listener

### LINKED ISSUE #201: Only the last 5 announcements are fetched from "loadannouncements" on app load/refresh
### Steps to reproduce
1. post more than 5 announcements
2. all announcements posted prior to refresh are shown
3. reload the page or navigate to the app after this

### Expected behaviour
I would expect to see all announcements

### Actual behaviour
Only the last 5 announcements are loaded

### Server configuration

**Operating system**:
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
19.0.0

### PR DESCRIPTION
**Pull request by SLYtiger16**
Signed-off-by: Kyle Meadows <Kyle.Meadows@610ind.com>

This PR fixes #201 by correcting a broken scroll listener to allow for lazy-loading more announcements on scroll as code intended originally.
Additionally, this adds a notification when more announcements are loading to give the user better feedback

### CODE REVIEW

**Comment by dirdi** [comment]
Thanks for working on bug #201, which also affects me! Most changes of this PR consist of added spaces and newlines. Beside that you removed the trailing newline at EOF of js/script.js. I think this PR would have better chances to get merged if it contained only changes necessary to fix the actual bug.

File: templates/main.php [hunk 1]
```diff
@@ -32,6 +32,10 @@
 		<h2><?php p($l->t('No Announcements')); ?></h2>
 		<p><?php p($l->t('There are currently no announcements…')); ?></p>
 	</div>
+	
+	<div id="lazyload" class="hidden">
+		<input type="button" id="lazyload_button" value="<?php p($l->t('Loading More Announcements...')); ?>" name="lazyload" />
```
Comment (nickvergessen) [inline templates/main.php:37]:
```suggestion
		<input type="button" id="lazyload_button" value="<?php p($l->t('Loading More Announcements …')); ?>" name="lazyload" />
```
